### ISSUE TITLE
NAutoContainer.cs uses non-concurrent Dictionary, which can cause deadlocking

### ISSUE THREAD

**Issue by td444** [amido/NAuto#1]
https://github.com/amido/NAuto/blob/master/Amido.NAuto/Nject/NAutoContainer.cs

When running tests with concurrency (e.g. NCrunch), this could lead to random deadlocking and invalidate test runs as a result.

See http://blogs.msdn.com/b/tess/archive/2009/12/21/high-cpu-in-net-app-using-a-static-generic-dictionary.aspx

**Comment by iamkoch** [comment]
This can be closed now
